// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Token)(nil), "user.Token")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8f, 0x4d, 0x6b, 0x83, 0x40,
	0x10, 0x86, 0xf1, 0xab, 0xe0, 0x14, 0x7a, 0x58, 0x7a, 0x90, 0x42, 0x8b, 0x78, 0x12, 0x8a, 0x6e,
	0xb1, 0xf9, 0x01, 0x21, 0x97, 0xdc, 0x4d, 0x72, 0xc9, 0x6d, 0x75, 0x07, 0xdd, 0x24, 0xba, 0xb2,
	0x3b, 0x1e, 0xf2, 0xef, 0xc3, 0xae, 0xb7, 0xf7, 0x19, 0xe6, 0x99, 0x0f, 0x80, 0xd5, 0xa2, 0xa9,
	0x17, 0xa3, 0x49, 0xb3, 0xd8, 0xe5, 0x62, 0x0f, 0xf1, 0xc5, 0xa2, 0x61, 0x1f, 0x10, 0x2a, 0x99,
	0x05, 0x79, 0x50, 0x26, 0x6d, 0xa8, 0x24, 0xfb, 0x84, 0x04, 0x27, 0xa1, 0x1e, 0x59, 0x98, 0x07,
	0x65, 0xda, 0x6e, 0xc0, 0x18, 0xc4, 0xb3, 0x98, 0x30, 0x8b, 0x7c, 0xd1, 0xe7, 0xe2, 0x1b, 0x92,
	0xb3, 0xbe, 0xe3, 0xec, 0x14, 0x72, 0xc1, 0x4f, 0x49, 0xdb, 0x0d, 0x9a, 0x5f, 0x48, 0xdd, 0x82,
	0x13, 0x69, 0x83, 0xec, 0x07, 0xa2, 0x23, 0x12, 0x7b, 0xaf, 0xfd, 0x1d, 0x5e, 0xfb, 0x82, 0x0d,
	0x5c, 0xd3, 0xa1, 0xb9, 0xfe, 0x0d, 0x8a, 0xc6, 0xb5, 0xab, 0x7b, 0x3d, 0xf1, 0x41, 0xda, 0xbe,
	0x7a, 0x5a, 0x6e, 0x17, 0xa3, 0x66, 0xda, 0x55, 0x37, 0x65, 0x44, 0x45, 0xa3, 0x41, 0x21, 0xb9,
	0x58, 0x69, 0xe4, 0x4e, 0xec, 0xde, 0xfc, 0x3b, 0xff, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x43, 0xea, 0xd8, 0xdc, 0x00, 0x00, 0x00,
}
